<?php

return [

    'default_device_id' => env('AI_CORE_DEFAULT_DEVICE_ID', 'default-device'),

    'intents' => [
        'reminder.create' => [
            'patterns' => [
                'remind me to {title}',
                'remind me {title}',
                'set a reminder',
                'reminder to {title}',
            ],
            'keywords' => ['remind', 'reminder', 'remind me'],
            'weight' => 10,
        ],
        'alarm.create' => [
            'patterns' => [
                'set an alarm',
                'alarm for {time}',
                'wake me at {time}',
                'wake me up at {time}',
            ],
            'keywords' => ['alarm', 'wake', 'wake me'],
            'weight' => 10,
        ],
        'datetime.read' => [
            'patterns' => [
                'what time is it',
                'what is the date',
                'current time',
                'what time is now',
            ],
            'keywords' => ['time', 'date', 'what time', 'current time'],
            'weight' => 10,
        ],
        'call.make' => [
            'patterns' => [
                'call {contact}',
                'call {phone_number}',
                'dial {phone_number}',
                'make a call',
            ],
            'keywords' => ['call', 'dial', 'make a call'],
            'weight' => 10,
        ],
        'call.end' => [
            'patterns' => [
                'end the call',
                'hang up',
                'stop the call',
                'end call',
            ],
            'keywords' => ['end call', 'hang up', 'end the call', 'stop call'],
            'weight' => 10,
        ],
        'contact.search' => [
            'patterns' => [
                'find {query}',
                'search for {query}',
                'find contact {query}',
            ],
            'keywords' => ['find', 'search contact', 'look up'],
            'weight' => 8,
        ],
        'contact.list' => [
            'patterns' => [
                'list contacts',
                'show contacts',
                'my contacts',
            ],
            'keywords' => ['contacts', 'contact list', 'show contacts'],
            'weight' => 8,
        ],
        'device.volume' => [
            'patterns' => [
                'turn up volume',
                'turn down volume',
                'set volume to {level}',
                'increase volume',
                'lower volume',
            ],
            'keywords' => ['volume', 'turn up', 'turn down', 'increase', 'lower'],
            'weight' => 9,
        ],
        'device.flashlight' => [
            'patterns' => [
                'flashlight on',
                'flashlight off',
                'turn on flashlight',
                'turn off flashlight',
                'torch on',
                'torch off',
            ],
            'keywords' => ['flashlight', 'torch'],
            'weight' => 9,
        ],
        'device.wifi' => [
            'patterns' => [
                'turn on wifi',
                'turn off wifi',
                'enable wifi',
                'disable wifi',
            ],
            'keywords' => ['wifi', 'wi-fi'],
            'weight' => 8,
        ],
        'device.bluetooth' => [
            'patterns' => [
                'turn on bluetooth',
                'turn off bluetooth',
                'enable bluetooth',
                'disable bluetooth',
            ],
            'keywords' => ['bluetooth'],
            'weight' => 8,
        ],
        'device.brightness' => [
            'patterns' => [
                'set brightness to {level}',
                'brightness {level}',
                'screen brightness',
            ],
            'keywords' => ['brightness', 'screen brightness'],
            'weight' => 7,
        ],
        'device.lock' => [
            'patterns' => [
                'lock the device',
                'lock screen',
                'screen lock',
            ],
            'keywords' => ['lock', 'lock screen'],
            'weight' => 7,
        ],
        'notification.list' => [
            'patterns' => [
                'show notifications',
                'list notifications',
                'my notifications',
                'read notifications',
            ],
            'keywords' => ['notification', 'notifications'],
            'weight' => 8,
        ],
        'app.open' => [
            'patterns' => [
                'open {app}',
                'launch {app}',
                'open app {app}',
            ],
            'keywords' => ['open', 'launch'],
            'weight' => 9,
        ],
        'robot.idle' => [
            'patterns' => [
                'go idle',
                'rest now',
                'robot idle',
            ],
            'keywords' => ['idle', 'rest', 'sleep'],
            'weight' => 7,
        ],
        'robot.talking' => [
            'patterns' => [
                'start talking',
                'stop talking',
                'robot speaking',
            ],
            'keywords' => ['talking', 'speak', 'speaking'],
            'weight' => 6,
        ],
        'robot.wake' => [
            'patterns' => [
                'wake up',
                'robot wake',
                'awaken',
            ],
            'keywords' => ['wake', 'awake', 'awaken'],
            'weight' => 7,
        ],
        'battery.status' => [
            'patterns' => [
                'battery level',
                'how much battery',
                'battery status',
            ],
            'keywords' => ['battery', 'charge'],
            'weight' => 8,
        ],
        'memory.store' => [
            'patterns' => [
                'remember that {fact}',
                'remember {fact}',
                'store this',
                'save this',
            ],
            'keywords' => ['remember', 'remember that', 'save', 'store'],
            'weight' => 6,
        ],
        'memory.retrieve' => [
            'patterns' => [
                'what did you say',
                'what did we talk about',
                'do you remember',
            ],
            'keywords' => ['remember', 'recall', 'what did', 'do you remember'],
            'weight' => 5,
        ],
        'conversation.clear' => [
            'patterns' => [
                'start over',
                'new conversation',
                'clear chat',
                'restart',
            ],
            'keywords' => ['start over', 'new conversation', 'clear', 'restart'],
            'weight' => 5,
        ],
    ],

    'entity_patterns' => [
        'phone_number' => '/(\+?\d{1,3}[\s\-\.]?)?\(?\d{3,4}\)?[\s\-\.]?\d{3}[\s\-\.]?\d{4}/',
        'time' => '/\b(\d{1,2})(?::(\d{2}))?\s*(am|pm)?\b/i',
        'datetime' => '/\b(\d{4}[\/\-]\d{1,2}[\/\-]\d{1,2}[\sT]\d{1,2}:\d{2}(:\d{2})?)\b|\b(\d{1,2}[\/\-]\d{1,2}[\/\-]\d{4})\b/',
        'level' => '/\b(\d{1,3})\s*%?\b/',
        'reminder_title' => '/(?:remind(?:er)?(?:\s+me)?\s+to)\s+(.+?)(?:\s+at\s+|$) /i',
    ],

    'flowchart' => [
        'reminder.create' => [
            'tool' => 'time',
            'group' => 'T1',
            'action' => 'set_reminder',
            'endpoint' => '/api/tools/time/t1/reminders',
            'requires_device_permission' => true,
            'entities' => ['title', 'scheduled_at'],
            'description' => 'Queue a reminder on the device',
        ],
        'alarm.create' => [
            'tool' => 'time',
            'group' => 'T2',
            'action' => 'set_alarm',
            'endpoint' => '/api/tools/time/t2/alarms',
            'requires_device_permission' => true,
            'entities' => ['time'],
            'description' => 'Queue an alarm on the device',
        ],
        'datetime.read' => [
            'tool' => 'time',
            'group' => 'T3',
            'action' => 'date_time',
            'endpoint' => '/api/tools/time/t3/date-time',
            'requires_device_permission' => false,
            'entities' => [],
            'description' => 'Retrieve current date and time',
        ],
        'call.make' => [
            'tool' => 'phone',
            'group' => 'P2',
            'action' => 'make_call',
            'endpoint' => '/api/tools/phone/p2/calls',
            'requires_device_permission' => true,
            'entities' => ['phone_number', 'contact'],
            'description' => 'Make a phone call',
        ],
        'call.end' => [
            'tool' => 'phone',
            'group' => 'P2',
            'action' => 'end_call',
            'endpoint' => '/api/tools/phone/p2/calls',
            'requires_device_permission' => true,
            'entities' => ['call_id'],
            'description' => 'End an active phone call',
        ],
        'contact.search' => [
            'tool' => 'phone',
            'group' => 'P3',
            'action' => 'contacts_search',
            'endpoint' => '/api/tools/phone/p3/contacts',
            'requires_device_permission' => true,
            'entities' => ['query'],
            'description' => 'Search contacts on the device',
        ],
        'contact.list' => [
            'tool' => 'phone',
            'group' => 'P3',
            'action' => 'contacts_list',
            'endpoint' => '/api/tools/phone/p3/contacts',
            'requires_device_permission' => true,
            'entities' => ['limit'],
            'description' => 'List contacts on the device',
        ],
        'device.volume' => [
            'tool' => 'phone',
            'group' => 'P4',
            'action' => 'set_volume',
            'endpoint' => '/api/tools/phone/p4/device-actions',
            'requires_device_permission' => true,
            'entities' => ['level'],
            'description' => 'Set device volume',
        ],
        'device.flashlight' => [
            'tool' => 'phone',
            'group' => 'P4',
            'action' => 'flashlight',
            'endpoint' => '/api/tools/phone/p4/device-actions',
            'requires_device_permission' => true,
            'entities' => ['enabled'],
            'description' => 'Toggle device flashlight',
        ],
        'device.wifi' => [
            'tool' => 'phone',
            'group' => 'P4',
            'action' => 'set_wifi',
            'endpoint' => '/api/tools/phone/p4/device-actions',
            'requires_device_permission' => true,
            'entities' => ['enabled'],
            'description' => 'Toggle device Wi-Fi',
        ],
        'device.bluetooth' => [
            'tool' => 'phone',
            'group' => 'P4',
            'action' => 'set_bluetooth',
            'endpoint' => '/api/tools/phone/p4/device-actions',
            'requires_device_permission' => true,
            'entities' => ['enabled'],
            'description' => 'Toggle device Bluetooth',
        ],
        'device.brightness' => [
            'tool' => 'phone',
            'group' => 'P4',
            'action' => 'set_brightness',
            'endpoint' => '/api/tools/phone/p4/device-actions',
            'requires_device_permission' => true,
            'entities' => ['level'],
            'description' => 'Set device screen brightness',
        ],
        'device.lock' => [
            'tool' => 'phone',
            'group' => 'P4',
            'action' => 'lock_device',
            'endpoint' => '/api/tools/phone/p4/device-actions',
            'requires_device_permission' => true,
            'entities' => [],
            'description' => 'Lock the device screen',
        ],
        'notification.list' => [
            'tool' => 'phone',
            'group' => 'P5',
            'action' => 'notifications_list',
            'endpoint' => '/api/tools/phone/p5/notifications',
            'requires_device_permission' => true,
            'entities' => ['limit'],
            'description' => 'List notifications on the device',
        ],
        'app.open' => [
            'tool' => 'phone',
            'group' => 'P1',
            'action' => 'open_app',
            'endpoint' => '/api/tools/phone/p1/open-app',
            'requires_device_permission' => true,
            'entities' => ['app'],
            'description' => 'Open an app on the device',
        ],
        'robot.idle' => [
            'tool' => 'robot',
            'group' => 'R1',
            'action' => 'robot_idle',
            'endpoint' => '/api/tools/robot/r1/idle',
            'requires_device_permission' => false,
            'entities' => ['level'],
            'description' => 'Set robot to idle animation',
        ],
        'robot.talking' => [
            'tool' => 'robot',
            'group' => 'R2',
            'action' => 'robot_talking',
            'endpoint' => '/api/tools/robot/r2/talking',
            'requires_device_permission' => false,
            'entities' => ['while_speaking', 'level'],
            'description' => 'Play robot talking animation',
        ],
        'robot.wake' => [
            'tool' => 'robot',
            'group' => 'R3',
            'action' => 'robot_wake',
            'endpoint' => '/api/tools/robot/r3/wake',
            'requires_device_permission' => false,
            'entities' => ['source', 'level'],
            'description' => 'Play robot wake animation',
        ],
        'battery.status' => [
            'tool' => 'battery',
            'group' => 'B1',
            'action' => 'battery_status',
            'endpoint' => '/api/tools/battery/b1/charging-started',
            'requires_device_permission' => true,
            'entities' => ['level'],
            'description' => 'Report battery status',
        ],
        'memory.store' => [
            'tool' => 'ai-core',
            'group' => 'M1',
            'action' => 'memory_store',
            'endpoint' => '/api/ai-core/memory/store',
            'requires_device_permission' => false,
            'entities' => ['fact'],
            'description' => 'Store a memory',
        ],
        'memory.retrieve' => [
            'tool' => 'ai-core',
            'group' => 'M2',
            'action' => 'memory_retrieve',
            'endpoint' => '/api/ai-core/memory/retrieve',
            'requires_device_permission' => false,
            'entities' => ['query'],
            'description' => 'Retrieve a memory',
        ],
    ],

    'gemini' => [
        'enabled' => env('GEMINI_ENABLED', true),
        'api_key' => env('GEMINI_API_KEY', ''),
        'model' => env('GEMINI_MODEL', 'gemini-2.5-flash'),
        'timeout' => (int) env('GEMINI_TIMEOUT', 60),
        'system_prompt' => env('GEMINI_SYSTEM_PROMPT', 'You are a helpful AI assistant named Boogy. Be concise, friendly, and helpful.'),
        'max_context_messages' => (int) env('GEMINI_MAX_CONTEXT_MESSAGES', 10),
    ],
];
